(include "../functions/make-binary-tree.rkt")

(define tree (make-binary-tree))

(equal? (tree 'height) 0)
(tree 'insert '(10 20 5 30 2))
(equal? (tree 'height) 3)
(not (tree 'find 55))
(not (equal? (tree 'find 5) #f))
(equal? (list (tree 'find 55) (tree 'find 5)) (tree 'find '(55 5)))
(equal? (tree) '(2 5 10 20 30))
(equal? (tree 'find-min) (tree 'find (apply min (tree))))
(equal? (tree 'find-max) (tree 'find (apply max (tree))))
(tree 'delete '(20 2))
(tree 'insert 2)
(equal? (tree) '(2 5 10 30))
(tree 'delete 10)
(equal? (tree) '(2 5 30))
(tree 'delete '(5 30 2))
(equal? (tree) (list))