(include "../functions/make-queue.rkt")

(define q1 (make-queue))
(equal? (q1 'pop) 'NULL)
(q1 'push 10)
(q1 'push 20)
(equal? (q1 'pop) 10)
(q1 'push 30)
(equal? (q1 'pop) 20)
(equal? (q1 'pop) 30)
(q1 'push 40)
(equal? (q1 'pop) 40)
(equal? (q1 'pop) 'NULL)
(equal? (q1 'empty?) #t)